# Generated by Django 3.1.7 on 2021-02-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
