# Generated by Django 3.1.7 on 2021-02-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharing',
            old_name='s_teacher',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='sharing',
            old_name='s_student',
            new_name='username',
        ),
    ]
